### ISSUE TITLE
bro以为自己发个github就是高贵开发者

### ISSUE THREAD

**Issue by HereisFrank9527** [Estrella-Explore/gcc_strict-flags#1]
代码比readme都短，笑死我了

**Comment by Estrella-Explore** [comment]
> Raw comment(offiensive) :
> 
> > Source code is shorter than README, LMFAO

@HereisFrank9527 

offensive noob and a downright IDIOT

your protein in your sperm is MUCH MORE than in your silly brain, u totally scum.

**Comment by Estrella-Explore** [comment]
@HereisFrank9527 

look at your nerd question and your trash question

https://help.railway.app/questions/save-my-flask-9459916e
